"""Shared fixtures for the Phase 2 upstream engine-contract suite.

This conftest must stay importable under the system Python 3.11 product suite
(where every test module in this directory skips at collection time), so at
module level it only touches ``os.environ`` and defines fixtures whose bodies
lazily import the engine packages.

Offline contract: dummy LLM credentials are installed via
``os.environ.setdefault`` BEFORE any ``agentsociety2`` import can happen —
``import agentsociety2`` raises at module load when AGENTSOCIETY_LLM_API_KEY
is unset (agentsociety2/config/config.py:490-500). No test in this directory
performs network I/O or real LLM calls.

Run with the pinned engine environment:

    /home/user/engine-env/bin/python -m pytest tests/engine_contracts -q
"""

from __future__ import annotations

import asyncio
import os
import sys

import pytest

# ---------------------------------------------------------------------------
# Environment: MUST run before any agentsociety2 import anywhere in the session.
# setdefault only — never clobber a caller-provided real configuration.
# ---------------------------------------------------------------------------
os.environ.setdefault("AGENTSOCIETY_LLM_API_KEY", "dummy")
os.environ.setdefault("AGENTSOCIETY_LLM_API_BASE", "http://localhost:9")
# Config.LLM_RAY_MAX_WORKERS is bound at agentsociety2 import time
# (config.py:304: _env_int_or_cpu) and becomes ray.init(num_cpus=...) in
# init_dispatchers (llm_dispatcher.py:589-596). 2 == the bounded-concurrency
# contract exercised by test_agentsociety_concurrency_contracts.py.
os.environ.setdefault("AGENTSOCIETY_LLM_RAY_MAX_WORKERS", "2")
# Mirror upstream's hermetic test env (agentsociety2 tests/conftest.py).
os.environ.setdefault("AGENTSOCIETY_TRACE_WRITER_ASYNC", "0")
os.environ.setdefault("MEM0_TELEMETRY", "False")
os.environ.setdefault("ANONYMIZED_TELEMETRY", "False")


# ---------------------------------------------------------------------------
# Custom probe agent, registered through the stock custom/ scanner route.
#
# Route chosen (least invasive; see audit AGENTSOCIETY_AUDIT.md §A Option 2 +
# caveat 5): the runner resolves agent classes INSIDE each Ray task via the
# module registry (agent/runner.py:67-94), and the registry in a fresh worker
# process discovers ``custom/agents/*.py`` under the WORKSPACE_PATH env var
# (registry/base.py:170-196). Driver env vars, including WORKSPACE_PATH, are
# copied into Ray workers by init_dispatchers' job config
# (config/llm_dispatcher.py:551-567). Monkeypatch-registering in the driver
# registry would NOT propagate to worker processes, so the scanner route is
# the only zero-upstream-change route that works across the Ray boundary.
#
# Scanner acceptance rules (backend/services/custom/compatibility.py:198-303):
# must override to_workspace/ask/step, be no-arg constructible, and have a
# non-empty description — hence the docstring below.
# ---------------------------------------------------------------------------
CONTRACT_PROBE_AGENT_SOURCE = '''
"""Engine-contract probe agent (generated by tests/engine_contracts/conftest.py)."""

import json
import os
import time
from pathlib import Path

from agentsociety2.agent.base.agent import AgentBase


class ContractProbeAgent(AgentBase):
    """Contract probe agent: records workspace evidence for engine-contract tests."""

    async def to_workspace(self, workspace_path):
        workspace_path = Path(workspace_path)
        if self._workspace_root is None:
            self._bind_workspace(workspace_path)
        self.persist_agent_json(tick=None, t=self._current_time)

    async def ask(self, message, readonly=True, *, t=None):
        return f"probe:{self.id}:{message}"

    async def step(self, tick, t):
        self._step_count += 1
        self._current_time = t
        behavior = str((self._config or {}).get("behavior", "ok"))
        if behavior == "fail":
            raise RuntimeError(f"CONTRACT_PROBE_FAILURE agent {self.id}")
        sleep_s = float((self._config or {}).get("sleep_s", 0.0) or 0.0)
        started = time.time()
        with self.trace_span(
            "contract.step",
            attributes={"agent.step_count": self._step_count, "tick": tick},
        ):
            if sleep_s:
                # Deliberate BLOCKING sleep: occupies this batch task's worker
                # slot for the wall-clock duration (concurrency-bound probe).
                time.sleep(sleep_s)
        stopped = time.time()
        state_dir = self.workspace_root_path() / "state"
        payload = {
            "id": self.id,
            "tick": tick,
            "t": t.isoformat(),
            "pid": os.getpid(),
            "start": started,
            "stop": stopped,
            "step_count": self._step_count,
        }
        tmp = state_dir / f".step_{self._step_count:04d}.json.tmp"
        tmp.write_text(json.dumps(payload), encoding="utf-8")
        os.replace(tmp, state_dir / f"step_{self._step_count:04d}.json")
        return f"stepped:{self.id}:{self._step_count}"
'''


@pytest.fixture(scope="session")
def ray_engine(tmp_path_factory):
    """One local Ray runtime per session, started through the stock upstream path.

    - Creates the session workspace root with ``custom/agents/`` +
      ``custom/envs/`` and writes the probe agent file.
    - Sets WORKSPACE_PATH (must precede init_dispatchers so it is captured
      into the Ray job config env passthrough).
    - Runs ``init_dispatchers()`` exactly once (ray.init with
      num_cpus=AGENTSOCIETY_LLM_RAY_MAX_WORKERS=2).

    Skips (with the captured error) if Ray cannot start in this sandbox.
    """
    if sys.version_info < (3, 12):  # pragma: no cover - engine env is 3.12
        pytest.skip("engine contracts require Python >= 3.12")
    pytest.importorskip("agentsociety2", exc_type=ImportError)
    ray = pytest.importorskip("ray", exc_type=ImportError)

    root = tmp_path_factory.mktemp("as2_contract_workspace")
    agents_dir = root / "custom" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    (root / "custom" / "envs").mkdir(parents=True, exist_ok=True)
    (agents_dir / "contract_probe_agent.py").write_text(
        CONTRACT_PROBE_AGENT_SOURCE, encoding="utf-8"
    )

    prior_workspace = os.environ.get("WORKSPACE_PATH")
    os.environ["WORKSPACE_PATH"] = str(root)

    # Point the DRIVER registry at the same workspace via the public API so a
    # pre-test sanity resolve works in-process too (worker processes resolve
    # independently through the WORKSPACE_PATH env var copied by the job
    # config — registry/base.py:176-182).
    from agentsociety2.registry import get_registry

    get_registry().set_workspace(root)

    from agentsociety2.config.llm_dispatcher import init_dispatchers

    try:
        asyncio.run(init_dispatchers())
    except Exception as exc:  # noqa: BLE001 - sandbox capability probe
        pytest.skip(f"Ray could not start in this sandbox: {exc!r}")
    if not ray.is_initialized():  # pragma: no cover - defensive
        pytest.skip("Ray reported not initialized after init_dispatchers()")

    yield {
        "workspace_root": root,
        "agent_class_name": "ContractProbeAgent",
        "num_cpus": 2,
    }

    try:
        ray.shutdown()
    finally:
        if prior_workspace is None:
            os.environ.pop("WORKSPACE_PATH", None)
        else:
            os.environ["WORKSPACE_PATH"] = prior_workspace
